# Generated by Django 5.2.7 on 2025-10-07 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da categoria (ex: Python, Django)', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Identificador único para URLs', max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição opcional da categoria', max_length=500)),
                ('cor', models.CharField(default='#3498db', help_text='Cor em HEX para identidade visual', max_length=7)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título chamativo para o artigo', max_length=200)),
                ('slug', models.SlugField(help_text='URL amigável (gerado automaticamente)', max_length=200, unique_for_date='data_publicacao')),
                ('resumo', models.TextField(help_text='Breve resumo para previews e SEO', max_length=500)),
                ('conteudo', models.TextField(help_text='Conteúdo principal do artigo (suporta Markdown)')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('revisao', 'Em Revisão'), ('publicado', 'Publicado')], default='rascunho', help_text='Status de publicação', max_length=20)),
                ('destaque', models.BooleanField(default=False, help_text='Artigo em destaque na homepage')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_publicacao', models.DateTimeField(blank=True, help_text='Data de publicação (preenchido automaticamente)', null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('meta_descricao', models.CharField(blank=True, help_text='Descrição para SEO (até 300 caracteres)', max_length=300)),
                ('imagem_destaque', models.ImageField(blank=True, help_text='Imagem de destaque do artigo', null=True, upload_to='artigos/%Y/%m/')),
                ('tempo_leitura', models.PositiveIntegerField(default=5, help_text='Tempo estimado de leitura em minutos')),
                ('autor', models.ForeignKey(help_text='Autor do artigo', on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(help_text='Categoria principal do artigo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artigos', to='blog.categoria')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
                'ordering': ['-data_publicacao'],
                'indexes': [models.Index(fields=['status', 'data_publicacao'], name='blog_artigo_status_0fd81f_idx'), models.Index(fields=['slug', 'data_publicacao'], name='blog_artigo_slug_0edf17_idx')],
            },
        ),
    ]
